# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
