# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostlist',
            name='UI',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='app01.UserInfo'),
        ),
        migrations.AlterField(
            model_name='hostlist',
            name='dp',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app01.Depart'),
        ),
    ]
