# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.DePart')),
            ],
        ),
        migrations.AddField(
            model_name='grouphost',
            name='gh',
            field=models.ManyToManyField(to='app01.HostList'),
        ),
        migrations.AddField(
            model_name='grouphost',
            name='m',
            field=models.ManyToManyField(to='app01.GroupHost'),
        ),
    ]
