# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170523_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='uuu',
            field=models.ManyToManyField(to='app01.HostList'),
        ),
    ]
